# Generated by Django 2.1.7 on 2019-03-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_weave_app', '0003_character_offer_spell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
