# Generated by Django 2.1.7 on 2019-03-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_weave_app', '0004_auto_20190329_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='ciphertext',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='learned',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='level',
        ),
        migrations.AddField(
            model_name='spell',
            name='dict',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='runes',
            field=models.TextField(default=''),
        ),
    ]
